<?php

return [
    'home/index' => ['HomeController', 'index'],
    'auth/login' => ['AuthController', 'login'],
    'auth/register' => ['AuthController', 'register'],
    'auth/profile' => ['AuthController', 'profile'],
    'auth/logout' => ['AuthController', 'logout'],
    'wishlist/index' => ['WishlistController', 'index'],
    'scout/index' => ['ScoutController', 'index'],
    'admin/dashboard' => ['AdminController', 'dashboard'],
    'browse/index' => ['BrowseController', 'index'],
    'browse/detail' => ['BrowseController', 'detail'],
    'api/wishlist/add' => ['WishlistController', 'add'],
    'api/wishlist/remove' => ['WishlistController', 'remove'],
    'api/scout/save' => ['ScoutController', 'save'],
    'api/scout/delete' => ['ScoutController', 'delete'],
    'api/admin/create-user' => ['AdminController', 'createUser'],
    'api/admin/toggle-verification' => ['AdminController', 'toggleVerification'],
    'api/admin/delete-user' => ['AdminController', 'deleteUser'],
    'api/admin/approve-request' => ['AdminController', 'approveRequest'],
    'api/admin/reject-request' => ['AdminController', 'rejectRequest'],
    'api/admin/update-post' => ['AdminController', 'updatePost'],
    'api/admin/delete-post' => ['AdminController', 'deletePost'],
    'api/admin/delete-comment' => ['AdminController', 'deleteComment'],
    'api/browse/search' => ['BrowseController', 'search'],
    'api/comments/add' => ['CommentController', 'add'],
    'api/comments/delete' => ['CommentController', 'delete'],
];
